# rpc-router configuration
# The hybrid handler package names that is used for scanner during server startup. The more specific of package names, the faster to start
# List the package prefixes for all handlers used. Leave an empty array to indicate wildcard (all packages)
handlerPackages: ${rpc-router.handlerPackages:}
# The JSON RPC API path
jsonPath: ${rpc-router.jsonPath:/api/json}
# The form RPC API path
formPath: ${rpc-router.formPath:/api/form}
# if we want to register all handlers as services to the Consul for client to discover
registerService: ${rpc-router.registerService:false}
